spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brij2804/JavaRepo.git
          search-paths:
            - /Microservices/SpringbootMicroservicesPart8/git-localconfig-repo
          username:
          password:
server:
  port: 8888
#spring.cloud.config.server.git.uri=file:///C:/GitHubRepos/JavaRepo/Microservices/SpringbootMicroservicesPart8/git-localconfig-repo