spring:
  application:
    name: currency-exchange
  cloud:
    config:
      enabled: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8000
logging:
  level:
    org:
      springframework: debug