spring:
  application:
    name: limits-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  profiles:
    active: dev

limits-service:
  minimum: 2
  maximum: 998

#logging.level.org.springframework=debug